version: "3"
services:
    postgresdb:
        image: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        container_name: "nameInstance"
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: marvel

    adminer:
        image: adminer
        container_name: "adminermarvel"
        restart: always
        ports:
            - 8081:8080
volumes:
    db-data:
        driver: local
